export const motionConfig = {
  effects: {
    smooth: true,
    hero: true,
    parallax: true,
    story: true,
    stack: true,
    reveals: true,
  },
  desktop: "(min-width: 800px) and (min-height: 600px)",
  motionAllowed: "(prefers-reduced-motion: no-preference)",
  lenis: { lerp: 0.085, wheelMultiplier: 0.85 },
  hero: { distance: 65, duration: 1.25, stagger: 0.13, ease: "power3.out" },
  reveal: {
    duration: 0.65,
    distance: 28,
    ease: "power2.out",
    start: "top 92%",
  },
  parallax: {
    image: 15,
    imageScale: 1.1,
    ridge: -22,
    foreground: -40,
    copy: -100,
    start: "top top",
    end: "bottom top",
  },
  story: {
    scrollScreens: 2.8,
    scrub: 0.7,
    stepDuration: 1.4,
    transition: 0.3,
    distance: 35,
    maskDuration: 0.65,
    imageScale: 1.18,
    imageTravel: -4,
  },
  stack: {
    scale: 0.9,
    offset: -28,
    opacity: 0.6,
    scrub: 0.5,
    start: "top bottom",
    end: "top 18%",
  },
} as const;
